### ISSUE TITLE
Does it support mask input?

### ISSUE THREAD

**Issue by laidingq** [DimaChaichan/LAizypainter#1]
Does it support mask input? If possible, could you provide a workflow for masking input

**Comment by DimaChaichan** [comment]
Hello laidingq, 

What exactly do you mean by mask input? If your layer or document has an aplha channel, this is also sent to Comfy. Take a look at the Inpaint task as an example. https://github.com/DimaChaichan/LAizypainter/blob/main/doc%2Ftask.md#inpaint-1

You can also use a layer as a mask. It depends on your workflow. 
If you show me what your workflow looks like, I can tell you the best way to proceed. 

Best regards

**Comment by laidingq** [comment]
Thank you for your reply. I am a beginner and I will study the usage method carefully

**Comment by DimaChaichan** [comment]
Sure, let me know if you need help.

**Comment by laidingq** [comment]
I'm sorry, I don't know English. I used translation software to translate the language, and I'm not sure if I can express myself clearly.
I have studied the relevant workflows in your example and understood some of them. Currently, among the four paint workflows, I am not clear about the corresponding layers and mask relationships in Photoshop. If you have time, could you do a related graphic or video tutorial? Thank you very much for your excellent work.

**Comment by DimaChaichan** [comment]
Hello laidingq, 

I don't have a Tutorial. You will find a Demo Video here: https://www.linkedin.com/posts/demeter-chaichan-9a110156_photoshop-stablediffusion-comfyui-activity-7162689267452866560-VrZZ/?utm_source=share&utm_medium=member_desktop 

Show me your ComfyUI Workflow, then I can help you. Or show me what you want to do.

**Comment by laidingq** [comment]
Great, this is the video I need. I will study it seriously. Thank you very much

**Comment by laidingq** [comment]
Hello, excuse me. I have installed a plugin and cannot load files in the task folder. I can only import JSON files. How can I solve this problem? I have installed the latest downloaded plugin version
![QQ图片20240304231214](https://github.com/DimaChaichan/LAizypainter/assets/135723102/868c2cab-6e1b-4df4-bfa6-2c7da3ea7ca6)

**Comment by laidingq** [comment]
Hello, I'm sorry to bother you again. After reinstalling the plugin, I can now load the. lzy file normally. I want to modify partial content on a picture, but I still haven't figured out how to use it. If you have time, please give me some help. 
Thank you very much

**Comment by DimaChaichan** [comment]
Hello laidingq,

every lzy file is a Workflow (Task) in Comfui. In ComfyUI you can export workflows to use it for a API call. Comfui Example: https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

The lyz file have also a variables  part. This variables can replace values in the API Call  and appeares on the interface: https://github.com/DimaChaichan/LAizypainter?tab=readme-ov-file#task 

So, the idea of Laizypainter is now. You use a Task for one Special szenario. E.g do a Image 2 Image, Text 2 Image, etc. 
And you combine task wo get you result. 

You need to know about comfyui to be able to use this tool properly.

**Comment by DimaChaichan** [comment]
Hello laidingq,

the tool was primarily created for concept artists. 
What you want to do is an inpainting.
Comfyui workflow:
https://comfyanonymous.github.io/ComfyUI_examples/inpaint/

I would recommend the following project to solve tasks more easily: 
A1111: https://github.com/AUTOMATIC1111/stable-diffusion-webui
CushyStudio: https://github.com/rvion/CushyStudio 

If you want to use LaizyPainter you can use the following task:
Can you use one of these tasks: https://github.com/DimaChaichan/LAizypainter/blob/main/doc/task.md#inpaint

I use the Inpaint_select task here.
![Animation](https://github.com/DimaChaichan/LAizypainter/assets/16877719/ce914ad4-8624-47df-98ad-72fcf6ba63e0)

Hint, you need to use a Inpainting Model.

**Comment by laidingq** [comment]
Thank you very much for providing me with help. I have been learning comfyui for a while, but due to some work requirements, I need to use it in conjunction with PS. I think the plugin you created works well with comfyui, so I would like to learn how to use it. Seeing your prompt response and video production, I don't know how to express my gratitude to you.

**Comment by laidingq** [comment]
Hello, I apologize for bothering you again. After two days of exploration and based on your introduction and video, I have basically understood some of the usage of plugins. Now, I have a question that I still need to ask you:
In the text2image workflow, I ran the. lyz file you provided and obtained the resolution set in comfyui (1024x1024). The image resolution I wanted to generate was the same size as the canvas created in Photoshop. I saw in your instructions that "With # image. width #, # image. height # you get the current width and height from Image." I tried multiple times but was unsuccessful. I don't understand programming and hope to get your help.

**Comment by DimaChaichan** [comment]
Hello laidingq,

don't worry, I'm glad that someone is using the tool. So feel free to ask. 
But could you please always open new issues, that would be easier for me and others might have the same problem. 

To your question. 
You have found a bug. :D Thank you for that. Please use version. 0.0.3. Please also use the txt2img.lzy task from this release. Now everything should work again. :D
https://github.com/DimaChaichan/LAizypainter/releases

Many thanks

**Comment by laidingq** [comment]
I just installed the new version and found that the UI in Photoshop is getting confused。
![QQ截图20240307205810](https://github.com/DimaChaichan/LAizypainter/assets/135723102/e027b8e1-f9fe-4f46-b4e2-53c05d8668fa)
![QQ截图20240307205925](https://github.com/DimaChaichan/LAizypainter/assets/135723102/068f4fa2-ed94-47df-bdf8-05da00f14a1a)

**Comment by laidingq** [comment]
Everything is normal now, thank you very much。

**Comment by laidingq** [comment]
Hello, I'm sorry to bother you again. When I was using "inpaint. lzy"and"inpaint_layer".lzy, I noticed that there would be slight changes in the entire image. My understanding is that this workflow can change local areas of the image through "quick masking" in Photoshop, but I didn't get this result. I don't know if my understanding is correct. using"inpaint_select.lzy"and"inpaint_select_layer.lzy"Can obtain the correct results.

**Comment by DimaChaichan** [comment]
Hello laidingq, 

the behaviour is correct. 
The task "inpaint.lzy" uploads the entire document and the alpha is used as a mask. You can use it to create backgrounds, for example. 
![image](https://github.com/DimaChaichan/LAizypainter/assets/16877719/1d093d89-0a61-44ed-acef-8efa5a74e278)

With the "inpaint_layer" task, only the selected layer or the selected document is uploaded. Here you have to be a little careful, only the layer is really uploaded, which means that if the layer is smaller than your document, the result will also be smaller. 
![image](https://github.com/DimaChaichan/LAizypainter/assets/16877719/2dc83299-2ff8-49a4-9b62-79506b59e647)

Thanks for the feedback, I think I need to add this to the document. Maybe it also makes sense to see the uploaded images in the UI. 

I'm not currently working on the tool, but I'll write everything down and expand it. 
Since I don't know when I will continue working on it, maybe you can take a look at the tool. https://github.com/AbdullahAlfaraj/Comfy-Photoshop-SD
I haven't tested it myself yet.

Best regards

**Comment by laidingq** [comment]
Thank you for your answer. I have used almost all the plugins connected to Comfy UI and Photoshop, and in the end, I think the one you developed is particularly good, with great UI and features. I have also used Comfy Photoshop SD, but it cannot return images to Photoshop

**Comment by DimaChaichan** [comment]
Then I did a good job. :D 
Thanks and let me know if you need any more help,

**Comment by laidingq** [comment]
this is a great plugin and you are also an excellent developer. Thank you for your patient explanation. I cannot express my gratitude in words.
